apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thawzinmyo/sample-gitops.git
    targetRevision: HEAD
    path: k8s_manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
    name: development
  syncPolicy:
    syncOptions:
      - CreateNamespace=true